### ISSUE TITLE
jarsigner: unable to open jar file: app.aab

### ISSUE THREAD

**Issue by danielo515** [r0adkll/sign-android-release#10]
I'm getting the following error when trying to sign the app:

```
jarsigner: unable to open jar file: app.aab
```

This is my config 
```
- name: Sign app
    uses: r0adkll/sign-android-release@v1
    with:
          releaseDirectory: ./
          signingKeyBase64: ${{ secrets.ANDROID_SIGN_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets. KEY_PASS }}
```

I'm building an aab app. Maybe is that?
