### ISSUE TITLE
Verification failed error 

### ISSUE THREAD

**Issue by mitsest** [r0adkll/sign-android-release#17]
Hello, I 'm getting verification failed error at the zipalign step.

It only works if I add extractNativeLibs="true" to the application tag in AndroidManifest.xml.

I 'm using gradle 3.6.3

Any hints?

**Comment by villeraikko** [comment]
I'm suddenly having this same issue with APK built with Ionic / Cordova.

**Comment by villeraikko** [comment]
I can also confirm that adding `android:extractNativeLibs="true"` to my AndroidManifest.xml fixes the problem, but this makes the generated APK much larger.

**Comment by HEYGUL** [comment]
Hi,
I have the exact same issue,  but adding android:extractNativeLibs="true" to my AndroidManifest.xml does not fix the problem.
Here is my workflow configuration file:
```
name: Android Release

on:
  push:
    tags:
      - '*'

jobs:
  test_build_and_distribute:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew build

      - name: Unit Test
        run: ./gradlew testDebugUnitTest

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless

      - name: Build Release APK with Gradle
        run: ./gradlew assembleRelease

      - name: Sign Android release
        id: sign-android-app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: ./android/app/build/outputs/apk/release/
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          releaseNotesFile: CHANGELOG.md
          groups: testers
          file: ${{ steps.sign-android-app.outputs.signedReleaseFile }}
```

Any idea ?
