### ISSUE TITLE
Error: EACCES: permission denied, open 'app/build/outputs/bundle/release/signingKey.jks'

### ISSUE THREAD

**Issue by forntoh** [r0adkll/sign-android-release#22]
![image](https://user-images.githubusercontent.com/27886627/96013790-8f9a9a80-0e3d-11eb-906c-69f3ec7f15a7.png)

**Comment by forntoh** [comment]
Later, I tried chown
![image](https://user-images.githubusercontent.com/27886627/96017794-54e73100-0e42-11eb-8ab1-62396197da03.png)

**Comment by littlecorgi-twk** [comment]
me too. 
```yml
// android.yml
name: Android CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Build Android project"
        uses: vgaidarji/android-github-actions-build@v1.0.1
        with:
          args: "./gradlew assembleRelease"
      - name: Change Gradlew Permission
        run:
          chmod +x ./gradlew
      - name: "Sign Android release"
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
```

```text
// log:
Run r0adkll/sign-android-release@v1
  with:
    releaseDirectory: app/build/outputs/apk/release
    signingKeyBase64: ***
    alias: ***
    keyStorePassword: ***
    keyPassword: ***
Preparing to sign key @ app/build/outputs/apk/release with signing key
Error: EACCES: permission denied, open 'app/build/outputs/apk/release/signingKey.jks'
```
