### ISSUE TITLE
Error could not find semver

### ISSUE THREAD

**Issue by boswelja** [r0adkll/sign-android-release#27]
I've just started getting the following error when using this:
`Error: Could not find file '/home/runner/work/_actions/_temp_048ce8a4-bb03-49f4-855e-1f0b02f1614b/_staging/r0adkll-sign-android-release-d28dc26/node_modules/jest-snapshot/node_modules/.bin/semver'.`
I believe ff34f681c113c5965a5b44406bf0033326f29886 is the culprit, it appears semver was completely removed.

**Comment by seanwu1105** [comment]
Having the same error.

```
Download action repository 'r0adkll/sign-android-release@v1'
Error: Could not find file '/home/runner/work/_actions/_temp_a2cdbd55-181b-4601-b50e-54e5c932c6e6/_staging/r0adkll-sign-android-release-d28dc26/node_modules/jest-snapshot/node_modules/.bin/semver'.
```

The workflow file:

``` yml
- name: Sign release AAB
  uses: r0adkll/sign-android-release@v1
  with:
    releaseDirectory: ./android/app/build/outputs/bundle/release
    signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE_FILE }}
    alias: ${{ secrets.ANDROID_KEY_ALIAS }}
    keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
    keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
```

This action works fine before, but it broke this two hours ago.

**Comment by VladSumtsov** [comment]
Having the same issue. 
```
Download action repository 'r0adkll/sign-***-release@v1'
Error: Could not find file '/home/runner/work/_actions/_temp_ce5c90bd-16c3-46b8-8588-43c824c9cae0/_staging/r0adkll-sign-***-release-d28dc26/node_modules/jest-snapshot/node_modules/.bin/semver'.
```

The workflow file:
```
      - name: sign release build
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release/
          signingKeyBase64: ${{ secrets.SIGNING_KEY_BASE64 }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          signedReleaseFile: app/build/outputs/apk/release/app_release.apk
```

This action works fine yesterday and broke today.
