### ISSUE TITLE
Remove unsigned in name with action or in app

### ISSUE THREAD

**Issue by nilsi** [r0adkll/sign-android-release#37]
Hi,

The APK i built (with ./gradlew assembleProdRelease) in a previous step is named myapp-prod-release-**unsigned**.apk.
After I sign it with this plugin it becomes myapp-prod-release-**unsigned-signed**.apk

What is the prefer way to change the naming here?
Should I do this in my app's build.gradle file or is it something the action can do.

Thank you!

**Comment by yashovardhan99** [comment]
You can simply add an extra step to rename your file.
```yaml
- name: Rename APK
  run: mv ${{steps.sign_app.outputs.signedReleaseFile}} YOUR_FILE_HERE
```
You can also specify a name when exporting the artifact (depending on how you are exporting it).
For `actions/upload-artifact@v2`:-
```yaml
  - uses: actions/upload-artifact@v2
    with:
      name: Signed apk name
      path: ${{steps.sign_app.outputs.signedReleaseFile}}
```
