### ISSUE TITLE
[Question] How to retrieve a signed apk file?

### ISSUE THREAD

**Issue by X1nto** [r0adkll/sign-android-release#7]
Hi, I tried using this action but unfortunately I can't locate the apk file that's produced on commit push.
Here's the .yml file:
```
name: Signed APK Builder

on:
  push:
    branches:
      - master
       
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant rights
        run: chmod +x ./gradlew

      - name: Build project with Gradle
        run: ./gradlew build

      - name: Build Release APK with Gradle
        run: ./gradlew assembleRelease

      - uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/release
          signingKeyBase64: ${{ secrets.TOKEN }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
```
Am I missing something? Should I create tags or do something else?

**Comment by kceb** [comment]
@X1nto 

Utilize `id` and `outputs`
```
    - name: Sign Android App
      id: sign-android-app
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: ./android/app/build/outputs/apk/release/
        signingKeyBase64: ${{ secrets.APK_SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
    - name: Other Step that accepts file as an input and uploads it somewhere
      with:
        file: ${{ steps.sign-android-app.outputs.signedReleaseFile }}
```

Look into github action outputs if you aren't able to get it working

**Comment by X1nto** [comment]
Thank you very much! I'll try to use the code as an example and build system on top of it, will report if anything goes wrong. Thanks again

**Comment by X1nto** [comment]
Hi again. I made it working using GitHub artifacts:
```
- name: Upload file to github 
  uses: actions/upload-artifact@v2 
  with: 
    name: 'app-release' 
    path: ${{ steps.sign-app.outputs.signedReleaseFile }}
```
I'm closing issue, thanks for your help
