### ISSUE TITLE
Unable to sign APK file

### ISSUE THREAD

**Issue by Prin53** [r0adkll/sign-android-release#8]
I am using the action like:
```yaml
uses: r0adkll/sign-android-release@v1
with:
  releaseDirectory: ./
  signingKeyBase64: ${{ secrets.ANDROID_SIGNING_STORE }}
  alias: ${{ secrets.ANDROID_SIGNING_STORE_ALIAS }}
  keyStorePassword: ${{ secrets.ANDROID_SIGNING_STORE_PASS }}
  keyPassword: ${{ secrets.ANDROID_SIGNING_KEY_PASS }}
```
And getting the error:
> ##[error]There was an error when attempting to execute the process 'C:\Program Files (x86)\Android\android-sdk\build-tools\29.0.2\apksigner'. This may indicate the process failed to start. Error: spawn C:\Program Files (x86)\Android\android-sdk\build-tools\29.0.2\apksigner ENOENT

Notes:
- `runs-on: windows-latest` set for the job
- The APK placed at the repository root
- It works when trying to sign AAB file
