### ISSUE TITLE
zipalign not found cause signing failure

### ISSUE THREAD

**Issue by PINAKIN-KANSARA-EY** [r0adkll/sign-android-release#84]
Hi @r0adkll 
Signing was working find until yesterday. from today is giving below error.
This is a blocking issue. 

```
Error: Couldnt find the Android build tools @ /usr/local/lib/android/sdk/build-tools/30.0.2
Error: Unable to locate executable file: /usr/local/lib/android/sdk/build-tools/30.0.2/zipalign. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

**Comment by donatellijl12** [comment]
I have this issue as well and no change was made between runs using this task.

**Comment by marat2509** [comment]
Add env variable for use special build tools version:
```
      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
```

You can get build tools versions by 
```
ls /usr/local/lib/android/sdk/build-tools/
```
