### ISSUE TITLE
Your Android App Bundle has more than 1 certificate chain

### ISSUE THREAD

**Issue by linonetwo** [r0adkll/sign-android-release#88]
I encounter this when upload aab to the google play store. The ci is https://github.com/tiddly-gittly/TidGi-Mobile/blob/master/.github/workflows/build-f-droid-apk.yml

```yml
      - name: Build AAB
        run: |
          cd android
          # ./gradlew clean
          ./gradlew bundleRelease --no-daemon --warning-mode all

      - name: Sign AAB
        id: sign_app_aab
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: android/app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOLS_VERSION }}

      - name: Build APK
        run: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease --no-daemon --warning-mode all

      ## sign generated apk
      - name: Sign APK
        id: sign_app_apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOLS_VERSION }}

          
      - name: Show artifacts
        run: |
          ls android/app/build/outputs/apk/release/
          ls android/app/build/outputs/bundle/release/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          generate_release_notes: true
          files: |
            android/app/build/outputs/apk/release/app-release-signed.apk
            android/app/build/outputs/bundle/release/app-release.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
