### ISSUE TITLE
Issue signing aab

### ISSUE THREAD

**Issue by Surkhojb** [r0adkll/sign-android-release#93]
I've been struggling with this action to sign aab file.

The action works for all my other cases, debug, staging, release but when it comes to bundle I am facing and error during the signing step.

When I try to execute this block for bundle.

```    - name: Signing APK
        uses: Tlaster/android-sign@v1.2.2
        with:
          releaseDirectory: ./app/build/outputs/bundle/googleRelease
          signingKeyBase64: ${{ secrets.BUNDLE_SIGNING_KEY_STORE_BASE_64 }}
          output: build/release/signed
          alias: ${{ secrets.BUNDLE_SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.BUNDLE_SIGNING_STORE_PASSWORD }}
          keyPassword: ${{ secrets.BUNDLE_SIGNING_STORE_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
```

 I am getting the following error

```  C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\17.0.12-7\x64\bin\jarsigner.exe -verbose -sigalg SHA256withRSA -digestalg SHA-256 -keystore signingKey.jks -storepass *** -keypass *** Muslim-Pro-Android\build\outputs\bundle\googleRelease\app-google-release-signed.aab ***
jarsigner: unable to open jar file: app\build\outputs\bundle\googleRelease\app-google-release-signed.aab
Error: The process 'C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\17.0.12-7\x64\bin\jarsigner.exe' failed with exit code 1
``` 

Here is the release block that it works
```
 - name: Signing APK
      uses: Tlaster/android-sign@v1.2.2
      with:
        releaseDirectory: ./app/build/outputs/apk/google/release
        signingKeyBase64: ${{ secrets.RELEASE_SIGNING_KEY_STORE_BASE_64 }}
        output: build/release/signed
        alias: ${{ secrets.RELEASE_SIGNING_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.RELEASE_SIGNING_STORE_PASSWORD }}
        keyPassword: ${{ secrets.RELEASE_SIGNING_STORE_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "34.0.0"
```
